task_manager_core/urls.py
from django.contrib import admin
from django.urls import path, include

from users.views import CustomLoginView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/login/", CustomLoginView.as_view(), name="custom-login"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("tasks.urls", namespace="tasks")),
    path("workers/", include("users.urls", namespace="workers")),
]

tasks/urls.py
from django.urls import path

from tasks.views import (
    index,
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    toggle_status
)

urlpatterns = [
    path("", index, name="home"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/change-status/",
        toggle_status,
        name="task-change-status"
    ),
    path(
        "task-types/",
        TaskTypeListView.as_view(),
        name="task-type-list"
    ),
    path(
        "task-types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create"
    ),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update"
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete"
    ),
]

app_name = "tasks"

users/urls.py
from django.urls import path

from users.views import (
    WorkerListView,
    PositionListView,
    PositionDeleteView,
    PositionUpdateView,
    PositionCreateView,
    WorkerDetailView,
    WorkerUpdateView,
    WorkerCreateView,
    WorkerDeleteView
)


urlpatterns = [
    path("", WorkerListView.as_view(), name="worker-list"),
    path("<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("<int:pk>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path("create/", WorkerCreateView.as_view(), name="worker-create"),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list"
    ),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create"
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update"
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete"
    ),
]

app_name = "workers"

tasks/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _


class TaskType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ["name"]


class Task(models.Model):
    class PriorityChoice(models.IntegerChoices):
        URGENT = 0, _("Urgent")
        HIGH = 1, _("High")
        MEDIUM = 2, _("Medium")
        LOW = 3, _("Low")

    name = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateField()
    is_completed = models.BooleanField(default=False)
    priority = models.IntegerField(
        choices=PriorityChoice,
        default=PriorityChoice.MEDIUM
    )
    task_type = models.ForeignKey(
        TaskType, null=True,
        on_delete=models.SET_NULL,
        related_name="tasks"
    )
    assignees = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="tasks"
    )

    class Meta:
        ordering = ["is_completed", "priority", "deadline"]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Position(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ["name"]


class Worker(AbstractUser):
    position = models.ForeignKey(
        Position,
        null=True,
        on_delete=models.CASCADE,
        related_name="workers"
    )

    class Meta:
        ordering = ["username"]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from users.models import Worker, Position


class WorkerCreationForm(UserCreationForm):
    position = forms.ModelChoiceField(
        queryset=Position.objects.all(),
        widget=forms.RadioSelect
    )

    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "email",
            "position",
        )


class WorkerUpdateForm(forms.ModelForm):
    position = forms.ModelChoiceField(
        queryset=Position.objects.all(),
        widget=forms.RadioSelect
    )

    class Meta:
        model = Worker
        fields = ("username", "first_name", "last_name", "email", "position")

users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.db.models import Q
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic

from users.forms import WorkerCreationForm, WorkerUpdateForm
from users.models import Worker, Position


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker

    def get_queryset(self):
        queryset = get_user_model().objects.select_related("position").all()

        user_to_search = self.request.GET.get("name")
        if user_to_search:
            queryset = (
                queryset.filter(
                    Q(username__icontains=user_to_search)
                    | Q(first_name__icontains=user_to_search)
                    | Q(last_name__icontains=user_to_search)
                )
            )
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        user_to_search = self.request.GET.get("name")
        if user_to_search:
            context["user_to_search"] = user_to_search
        return context


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerUpdateForm

    def get_success_url(self):
        pk = self.kwargs.get("pk")
        return reverse_lazy("workers:worker-detail", args=[pk])


class WorkerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Worker
    form_class = WorkerCreationForm
    success_url = reverse_lazy("workers:worker-list")


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("workers:worker-list")


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("workers:position-list")


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("workers:position-list")


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("workers:position-list")


class CustomLoginView(LoginView):
    template_name = "registration/login.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("tasks:home")
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        to_remember = request.POST.get("remember")
        if to_remember:
            request.session.set_expiry(604800)
        else:
            request.session.set_expiry(0)
        return super().post(request, *args, **kwargs)

templates/users/position_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">{{ object|yesno:"Update,Create" }} position</h6>
          </div>
          <div class="card-body">
            <form method="post" action="" novalidate>
              {% csrf_token %}
              {{ form|crispy }}
              <input type="submit" value="{{ object|yesno:"Update,Create" }}" class="btn btn-primary float-right">

              <a href="{% url "workers:position-list" %}" class="btn btn-secondary">Cancel</a>

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/users/position_list.html
{% extends "base.html" %}
{% block content %}
  <div class="container-fluid">
    <h1 class="h3 mb-4 text-gray-800 d-flex justify-content-center">Positions
      <a href="{% url "workers:position-create" %}" class="ml-2" title="Create task type">
        <i class="fa fa-plus-circle"></i>
      </a>
    </h1>

    <div class="row">
      {% for pos in position_list %}
        <div class="col-xl-3 col-md-6 mb-4">
          <div class="card border-bottom-success shadow h-100 py-2">
            <div class="card-body">
              <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                  <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                    Position
                  </div>
                  <div class="h5 mb-0 font-weight-bold text-gray-800">{{ pos.name }}</div>
                </div>
                <div class="col-auto">
                  <a href="{% url "workers:position-update" pos.id %}" class="btn btn-secondary btn-circle btn-sm"
                     title="Edit task type">
                    <i class="fas fa-edit"></i>
                  </a>
                  <a href="#" class="btn btn-danger btn-circle btn-sm" data-toggle="modal"
                     title="Delete task type" data-target="#deleteType{{ pos.id }}">
                    <i class="fas fa-trash"></i>
                  </a>
                  {#                <i class="fas fa-tag fa-2x text-gray-300"></i>#}

                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="modal fade" id="deleteType{{ pos.id }}" tabindex="-1" role="dialog"
             aria-labelledby="DeleteTypeLabel"
             aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to delete the position?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
              <div class="modal-body">The position <strong>{{ task.name }}</strong> will be deleted!</div>
              <div class="modal-footer">
                <form method="post" action="{% url "workers:position-delete" pos.id %}">
                  {% csrf_token %}
                  <a class="btn btn-secondary" href="{% url "workers:position-list" %}">Cancel</a>
                  <input type="submit" value="Delete" class="btn btn-danger">
                </form>
              </div>
            </div>
          </div>
        </div>
      {% empty %}
        <h3>No positions yet...</h3>
      {% endfor %}
    </div>


  </div>
{% endblock %}

templates/users/worker_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-lg-4">
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary d-flex justify-content-between align-items-center">
              <span>
                Worker profile
              </span>
              <div>
                <a href="{% url "workers:worker-update" worker.id %}"
                   class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
                  <i class="fas fa-edit fa-sm text-white-50 mr-1"></i>Edit profile</a>
                <a href="#" data-toggle="modal" data-target="#deleteWorker"
                   class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm">
                  <i class="fas fa-user-minus fa-sm text-white-50 mr-1"></i>Delete profile</a>
              </div>
            </h6>
          </div>
          <div class="card-body">
            <div class="text-center">
              <img src="{% static "img/undraw_profile.svg" %}" alt="User profile" height="200px">
              <h5 class="mt-3">{{ worker.first_name }} {{ worker.last_name }}</h5>
              <p class="text-muted">{{ worker.position }}</p>
              <hr>
              <p>
                <strong class="float-left">Email:</strong>
                <span class="float-right">{{ worker.email }}</span>
              </p>
            </div>
            <br>
            <hr>
            <div>
              <strong>Tasks:</strong>
              <div class="table-responsive mt-2">
                <table class="table table-bordered text-center" id="dataTable">
                  <thead>
                  <tr>
                    <th>Task</th>
                    <th>Priority</th>
                    <th>Status</th>
                    <th>Deadline</th>

                  </tr>
                  </thead>
                  <tbody>
                  {% for task in worker.tasks.all %}
                    <tr>
                      <td>
                        <a href="{% url "tasks:task-detail" task.id %}">
                          {{ task.name }}
                        </a>
                      </td>
                      <td>
                        <span class="badge badge-warning">{{ task.get_priority_display }}</span>
                      </td>
                      <td>
                        {% if task.is_completed %}
                          <span class="badge badge-success">Done</span>
                        {% else %}
                          <span class="badge badge-info">In progress</span>
                        {% endif %}
                      </td>
                      <td>
                        {{ task.deadline }}
                      </td>
                    </tr>
                  {% empty %}
                    <tr>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="deleteWorker" tabindex="-1" role="dialog" aria-labelledby="DeleteWorkerLabel"
         aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to delete the worker?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">The worker <strong>{{ worker.username }}</strong> will be deleted permanently!</div>
          <div class="modal-footer">
            <form method="post" action="{% url "workers:worker-delete" worker.id %}">
              {% csrf_token %}
              <a class="btn btn-secondary" href="{% url "workers:worker-detail" worker.id %}">Cancel</a>
              <input type="submit" value="Delete" class="btn btn-danger">
            </form>
          </div>
        </div>
      </div>
    </div>


  </div>

{% endblock %}

templates/users/worker_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">{{ object|yesno:"Update,Create" }} worker profile</h6>
          </div>
          <div class="card-body">
            <form method="post" action="" novalidate>
              {% csrf_token %}
              {{ form|crispy }}
              <input type="submit" value="{{ object|yesno:"Update,Create" }}" class="btn btn-primary float-right">
              {% if object %}
                <a href="{% url "workers:worker-detail" object.id %}" class="btn btn-secondary">Cancel</a>
              {% else %}
                <a href="{% url "workers:worker-list" %}" class="btn btn-secondary">Cancel</a>
              {% endif %}
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/users/worker_list.html
{% extends "base.html" %}
{% block search %}
  <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
        method="get" action="">
    <div class="input-group">
      {% if user_to_search %}
        <input type="text" class="form-control bg-light border-0 small" value="{{ user_to_search }}"
               aria-label="Search" aria-describedby="basic-addon2" name="name">
      {% else %}
        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for a worker..."
               aria-label="Search" aria-describedby="basic-addon2" name="name">
      {% endif %}
      <div class="input-group-append">
        <button class="btn btn-primary" type="submit">
          <i class="fas fa-search fa-sm"></i>
        </button>
      </div>
    </div>
  </form>
{% endblock %}
{% block content %}
  <div class="container-fluid">

    <!-- Page Heading -->

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Workers
          <a href="{% url "workers:worker-create" %}" class="ml-2" title="Add worker">
            <i class="fa fa-plus-circle"></i>
          </a>
        </h6>

      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered text-center" id="dataTable">
            <thead>
            <tr>
              <th>Profile</th>
              <th>Username</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Email</th>
              <th>Position</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
              <th>Profile</th>
              <th>Username</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Email</th>
              <th>Position</th>
            </tr>
            </tfoot>
            <tbody>
            {% for worker in worker_list %}
              <tr>
                <td>
                  <a href="{% url "workers:worker-detail" worker.id %}" class="btn btn-info btn-circle btn-sm"
                     title="Worker details">
                    <i class="fas fa-user"></i>
                  </a>
                </td>
                <td>
                  {% if user.username == worker.username %}
                    {{ worker.username }}(Me)
                  {% else %}
                    {{ worker.username }}
                  {% endif %}
                </td>
                <td>{{ worker.first_name }}</td>
                <td>{{ worker.last_name }}</td>
                <td>{{ worker.email }}</td>
                <td>{{ worker.position }}</td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>

  </div>
  <!-- /.container-fluid -->

{% endblock %}