task_manager_core/urls.py
from django.contrib import admin
from django.urls import path, include

from users.views import CustomLoginView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/login/", CustomLoginView.as_view(), name="custom-login"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("tasks.urls", namespace="tasks")),
    path("workers/", include("users.urls", namespace="workers")),
]

tasks/urls.py
from django.urls import path

from tasks.views import (
    index,
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    toggle_status
)

urlpatterns = [
    path("", index, name="home"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/change-status/",
        toggle_status,
        name="task-change-status"
    ),
    path(
        "task-types/",
        TaskTypeListView.as_view(),
        name="task-type-list"
    ),
    path(
        "task-types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create"
    ),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update"
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete"
    ),
]

app_name = "tasks"

users/urls.py
from django.urls import path

from users.views import (
    WorkerListView,
    PositionListView,
    PositionDeleteView,
    PositionUpdateView,
    PositionCreateView,
    WorkerDetailView,
    WorkerUpdateView,
    WorkerCreateView,
    WorkerDeleteView
)


urlpatterns = [
    path("", WorkerListView.as_view(), name="worker-list"),
    path("<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("<int:pk>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path("create/", WorkerCreateView.as_view(), name="worker-create"),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list"
    ),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create"
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update"
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete"
    ),
]

app_name = "workers"

tasks/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _


class TaskType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ["name"]


class Task(models.Model):
    class PriorityChoice(models.IntegerChoices):
        URGENT = 0, _("Urgent")
        HIGH = 1, _("High")
        MEDIUM = 2, _("Medium")
        LOW = 3, _("Low")

    name = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateField()
    is_completed = models.BooleanField(default=False)
    priority = models.IntegerField(
        choices=PriorityChoice,
        default=PriorityChoice.MEDIUM
    )
    task_type = models.ForeignKey(
        TaskType, null=True,
        on_delete=models.SET_NULL,
        related_name="tasks"
    )
    assignees = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="tasks"
    )

    class Meta:
        ordering = ["is_completed", "priority", "deadline"]

tasks/forms.py
from django import forms
from django.contrib.auth import get_user_model

from tasks.models import Task, TaskType


class TaskCreationForm(forms.ModelForm):
    description = forms.CharField(
        label="",
        widget=forms.Textarea(
            attrs={
                "rows": 3,
                "cols": 50,
                "placeholder": "Enter task description...",
            }
        ),
    )

    deadline = forms.DateField(
        widget=forms.DateInput(
            attrs={
                "class": "form-control",
                "type": "date",
            }
        )
    )
    is_completed = forms.BooleanField(
        widget=forms.CheckboxInput(
            attrs={
                "class": "form-check-input",
            }
        ),
        required=False,
    )

    task_type = forms.ModelChoiceField(
        queryset=TaskType.objects.all(),
        widget=forms.RadioSelect
    )

    priority = forms.ChoiceField(
        choices=Task.PriorityChoice,
        widget=forms.RadioSelect
    )

    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Task
        fields = "__all__"

tasks/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from tasks.forms import TaskCreationForm
from tasks.models import Task, TaskType


@login_required
def index(request):
    return render(request, "base.html")


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    paginate_by = 10

    def get_queryset(self):
        queryset = (
            Task.objects.
            prefetch_related("assignees").
            select_related("task_type").all()
        )

        task_to_search = self.request.GET.get("task")
        if task_to_search:
            queryset = (
                queryset.filter(
                    Q(name__icontains=task_to_search)
                    | Q(description__icontains=task_to_search)
                )
            )
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        task_to_search = self.request.GET.get("task")
        if task_to_search:
            context["task_to_search"] = task_to_search
        return context


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskCreationForm
    success_url = reverse_lazy("tasks:task-list")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskCreationForm

    def get_success_url(self):
        pk = self.kwargs.get("pk")
        return reverse_lazy("tasks:task-detail", args=[pk])


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("tasks:task-list")


class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    template_name = "tasks/task_type_list.html"


class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    fields = "__all__"
    template_name = "tasks/task_type_form.html"
    success_url = reverse_lazy("tasks:task-type-list")


class TaskTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = TaskType
    fields = "__all__"
    template_name = "tasks/task_type_form.html"
    success_url = reverse_lazy("tasks:task-type-list")


class TaskTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    success_url = reverse_lazy("tasks:task-type-list")
    template_name = None


@login_required
def toggle_status(request: HttpResponse, pk: int) -> HttpRequest:
    task = get_object_or_404(Task, pk=pk)
    task.is_completed = not task.is_completed
    task.save()
    return redirect("tasks:task-detail", pk=pk)

templates/tasks/task_detail.html
{% extends "base.html" %}
{% block content %}
  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-900">
        {{ task.name }}
      </h1>
      <div>
        {% if task.is_completed %}
          <a href="{% url "tasks:task-change-status" task.id %}"
             class="d-none d-sm-inline-block btn btn-sm btn-secondary shadow-sm">
            <i class="fas fa-arrow-circle-left fa-sm text-white-50 mr-1"></i>Undo</a>
        {% else %}
          <a href="{% url "tasks:task-change-status" task.id %}"
             class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm">
            <i class="fas fa-check fa-sm text-white-50 mr-1"></i>Mark as completed</a>
        {% endif %}
        <a href="{% url "tasks:task-update" task.id %}"
           class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
          <i class="fas fa-edit fa-sm text-white-50 mr-1"></i>Edit task</a>
        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm" data-toggle="modal"
           data-target="#deleteTask">
          <i class="fas fa-trash fa-sm text-white-50 mr-1"></i>Delete task</a>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6">
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Description</h6>
          </div>
          <div class="card-body">
            {{ task.description }}
          </div>
        </div>
      </div>
    </div>
    <!-- Content Row -->
    <div class="row">
      <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-bottom-{% if task.is_completed %}success{% else %}info{% endif %} shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div
                    class="text-xs font-weight-bold text-{% if task.is_completed %}success{% else %}info{% endif %} text-uppercase mb-1">
                  Status
                </div>
                <div class="h5 mb-0 font-weight-bold text-gray-800">
                  {% if task.is_completed %}
                    <span>Done</span>
                  {% else %}
                    <span>In progress</span>
                  {% endif %}
                </div>
              </div>
              <div class="col-auto">
                <i class="fas fa-laptop fa-2x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Earnings (Monthly) Card Example -->
      <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-bottom-warning shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                  Priority
                </div>
                <div class="h5 mb-0 font-weight-bold text-gray-800">{{ task.get_priority_display }}</div>
              </div>
              <div class="col-auto">
                <i class="fas fa-exclamation fa-2x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-bottom-danger shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">
                  Deadline
                </div>
                <div class="h5 mb-0 font-weight-bold text-gray-800">{{ task.deadline }}</div>
              </div>
              <div class="col-auto">
                <i class="fas fa-calendar fa-2x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-bottom-dark shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-dark text-uppercase mb-1">
                  Type
                </div>
                <div class="h5 mb-0 font-weight-bold text-gray-800">{{ task.task_type }}</div>
              </div>
              <div class="col-auto">
                <i class="fas fa-tag fa-2x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Workers

        </h6>

      </div>
      <div class="card-body">
        <div class="table-responsive text-center">
          <table class="table table-bordered" id="dataTable">
            <thead>
            <tr>
              <th>Profile</th>
              <th>Username</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Email</th>
              <th>Position</th>
            </tr>
            </thead>
            <tbody>
            {% for worker in task.assignees.all %}
              <tr>
                <td>
                  <a href="{% url "workers:worker-detail" worker.id %}" class="btn btn-info btn-circle btn-sm"
                     title="Worker details">
                    <i class="fas fa-user"></i>
                  </a>
                </td>
                <td>
                  {% if user.username == worker.username %}
                    {{ worker.username }}(Me)
                  {% else %}
                    {{ worker.username }}
                  {% endif %}
                </td>
                <td>{{ worker.first_name }}</td>
                <td>{{ worker.last_name }}</td>
                <td>{{ worker.email }}</td>
                <td>{{ worker.position }}</td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="modal fade" id="deleteTask" tabindex="-1" role="dialog" aria-labelledby="DeleteTaskLabel"
         aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to delete the task?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">The task <strong>{{ task.name }}</strong> will be deleted permanently!</div>
          <div class="modal-footer">
            <form method="post" action="{% url "tasks:task-delete" task.id %}">
              {% csrf_token %}
              <a class="btn btn-secondary" href="{% url "tasks:task-detail" task.id %}">Cancel</a>
              <input type="submit" value="Delete" class="btn btn-danger">
            </form>
          </div>
        </div>
      </div>
    </div>

  </div>


{% endblock %}

templates/tasks/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">{{ object|yesno:"Update,Create" }} task</h6>
          </div>
          <div class="card-body">
            <form method="post" action="" novalidate>
              {% csrf_token %}
              {{ form|crispy }}
              <input type="submit" value="{{ object|yesno:"Update,Create" }}" class="btn btn-primary float-right">
              {% if object %}
                <a href="{% url "tasks:task-detail" object.id %}" class="btn btn-secondary">Cancel</a>
              {% else %}
                <a href="{% url "tasks:task-list" %}" class="btn btn-secondary">Cancel</a>
              {% endif %}
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/tasks/task_list.html
{% extends "base.html" %}
{% block search %}
  <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
        method="get" action="">
    <div class="input-group">
      {% if task_to_search %}
        <input type="text" class="form-control bg-light border-0 small" value="{{ task_to_search }}"
             aria-label="Search" aria-describedby="basic-addon2" name="task">
        {% else %}
        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for a task..."
             aria-label="Search" aria-describedby="basic-addon2" name="task">
      {% endif %}
      <div class="input-group-append">
        <button class="btn btn-primary" type="submit">
          <i class="fas fa-search fa-sm"></i>
        </button>
      </div>
    </div>
  </form>
{% endblock %}
{% block content %}
  <h1 class="h3 mb-4 text-gray-800 d-flex justify-content-center">Tasks
    <a href="{% url "tasks:task-create" %}" class="ml-2" title="Create task">
      <i class="fa fa-plus-circle"></i>
    </a>
  </h1>
  <div class="row justify-content-center">

    {% for task in task_list %}
      <div class="col-lg-5">

        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">{{ task.name }}
              <span class="badge badge-warning">{{ task.get_priority_display }}</span>
              {% if task.is_completed %}
                <span class="badge badge-success">Done</span>
              {% else %}
                <span class="badge badge-info">In progress</span>
              {% endif %}
              <span class="badge badge-dark">{{ task.task_type }}</span>
            </h6>
          </div>
          <div class="card-body">
            <span class="badge badge-success">Deadline: {{ task.deadline }}</span>
            <div class="d-inline float-right">
              <a href="{% url "tasks:task-detail" task.id %}" class="btn btn-info btn-circle btn-sm"
                 title="Task details">
                <i class="fas fa-info"></i>
              </a>
            </div>
            <hr>
            {{ task.description }}
          </div>
        </div>

      </div>
      {% empty %}
      <h3>No tasks yet...</h3>
    {% endfor %}
  </div>
  <div class="d-flex justify-content-center">
    {% if is_paginated %}
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">
              <i class="fa fa-angle-left"></i>
            </a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a href="#" class="page-link">
              <i class="fa fa-angle-left"></i>
            </a>
          </li>
        {% endif %}
        <li class="page-item active bg-gradient-primary">
          <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
        </li>
        {% if page_obj.has_next %}
          <li class="page-item">
            <a href="?page= {{ page_obj.next_page_number }}" class="page-link">
              <i class="fa fa-angle-right"></i>
            </a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a href="#" class="page-link">
              <i class="fa fa-angle-right"></i>
            </a>
          </li>
        {% endif %}
      </ul>
    {% endif %}
  </div>


{% endblock %}

templates/tasks/task_type_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">{{ object|yesno:"Update,Create" }} task type</h6>
          </div>
          <div class="card-body">
            <form method="post" action="" novalidate>
              {% csrf_token %}
              {{ form|crispy }}
              <input type="submit" value="{{ object|yesno:"Update,Create" }}" class="btn btn-primary float-right">

              <a href="{% url "tasks:task-type-list" %}" class="btn btn-secondary">Cancel</a>

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/tasks/task_type_list.html
{% extends "base.html" %}
{% block content %}
  <div class="container-fluid">
    <h1 class="h3 mb-4 text-gray-800 d-flex justify-content-center">Task types
      <a href="{% url "tasks:task-type-create" %}" class="ml-2" title="Create task type">
        <i class="fa fa-plus-circle"></i>
      </a>
    </h1>

    <div class="row">
      {% for task in tasktype_list %}
        <div class="col-xl-3 col-md-6 mb-4">
          <div class="card border-bottom-dark shadow h-100 py-2">
            <div class="card-body">
              <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                  <div class="text-xs font-weight-bold text-dark text-uppercase mb-1">
                    Type
                  </div>
                  <div class="h5 mb-0 font-weight-bold text-gray-800">{{ task.name }}</div>
                </div>
                <div class="col-auto">
                  <a href="{% url "tasks:task-type-update" task.id %}" class="btn btn-secondary btn-circle btn-sm"
                     title="Edit task type">
                    <i class="fas fa-edit"></i>
                  </a>
                  <a href="#" class="btn btn-danger btn-circle btn-sm" data-toggle="modal"
                     title="Delete task type" data-target="#deleteType{{ task.id }}">
                    <i class="fas fa-trash"></i>
                  </a>
                  {#                <i class="fas fa-tag fa-2x text-gray-300"></i>#}

                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="modal fade" id="deleteType{{ task.id }}" tabindex="-1" role="dialog"
             aria-labelledby="DeleteTypeLabel"
             aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to delete the type?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
              <div class="modal-body">The task type <strong>{{ task.name }}</strong> will be deleted!</div>
              <div class="modal-footer">
                <form method="post" action="{% url "tasks:task-type-delete" task.id %}">
                  {% csrf_token %}
                  <a class="btn btn-secondary" href="{% url "tasks:task-type-list" %}">Cancel</a>
                  <input type="submit" value="Delete" class="btn btn-danger">
                </form>
              </div>
            </div>
          </div>
        </div>
      {% empty %}
        <h3>No task types yet...</h3>
      {% endfor %}
    </div>

  </div>

{% endblock %}